addons:
    apt:
        packages:
            - make
            - telnet

script: make remove && make test

branches:
    only:
        - master
        - develop

notifications:
    email:
        on_success: never
        on_failure: change
