addons:
    apt:
        packages:
            - make
            - telnet

script: make remove && make test

branches:
    only:
        - master

notifications:
    email:
        on_success: never
        on_failure: change
